### ISSUE TITLE
Provide dependencies as YAML file

### ISSUE THREAD

**Issue by denisbeslic** [Yan98/DPST#1]
Dear authors,

could you specify the exact dependencies needed for DPST using a YAML file, so the dependencies can be installed easily via conda? I'm having problems problems with installing the dependencies you specified in the readme file. Pytorch3d=0.6.0 seems to be incompatible with pytorch=1.9.1.

**Comment by Yan98** [comment]
Thanks for your interest. Have you tried to compile Pytorch3d from the source? https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md#building--installing-from-source

**Comment by denisbeslic** [comment]
Thank you that worked. :+1:
